name: "Greet Action"
description: "Greets someone and exposes a message output"
author: "GoodData"
inputs:
  name:
    description: "Name to greet"
    required: true
  jira-api-token:
    description: "Jira API token"
    required: true
  jira-email:
    description: "Jira user email"
    required: true
  slackbot-token:
    description: "Slack bot token"
    required: true
  github-token:
    description: "GitHub token"
    required: true
outputs:
  message:
    description: "Greeting that was produced"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "message-square"
  color: "blue"
